_wandb:
    value:
        cli_version: 0.25.0
        e:
            155ewqfdldx9wl4rf7d2cl3hjr3edwjs:
                args:
                    - --group
                    - 2_hyperparameter_sweep
                    - --activation=relu
                    - --batch_size=128
                    - --dataset=mnist
                    - --epochs=8
                    - --hidden_size=64
                    - --learning_rate=0.1
                    - --loss=cross_entropy
                    - --num_layers=5
                    - --optimizer=sgd
                    - --weight_decay=0.0001
                    - --weight_init=random
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1081101176832"
                        used: "8248598528"
                email: da25m031@smail.iitm.ac.in
                executable: /home/chava/da6401_assignment1/.venv/bin/python3
                git:
                    commit: 07f46cda842f0833a576b7427e83d0bd8ff4a415
                    remote: git@github.com:YashrajRC/da6401_Assignment1.git
                host: Yashraj
                memory:
                    total: "8138207232"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/chava/da6401_assignment1/src/train.py
                python: CPython 3.12.3
                root: /home/chava/da6401_assignment1
                startedAt: "2026-03-06T17:34:26.996482Z"
                writerId: 155ewqfdldx9wl4rf7d2cl3hjr3edwjs
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 14
                - 16
            "4": 3.12.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 128
dataset:
    value: mnist
epochs:
    value: 8
hidden_size:
    value: 64
learning_rate:
    value: 0.1
loss:
    value: cross_entropy
num_layers:
    value: 5
optimizer:
    value: sgd
weight_decay:
    value: 0.0001
weight_init:
    value: random
